from django.shortcuts import render, get_object_or_404
from .models import Module
from django.core import serializers
from django.http import HttpResponse
import string

LIST_OF_MODULES_TO_SEARCH = {
'abaqus' : ['finite element analysis', 'Engineering'],
'abinit' : ['Chemistry', 'materials modeling', 'density functional theory', 'optimization', 'simulation'],
'ADF' : ['Chemistry', 'Molecular Dynamics', 'quantum mechanics', 'density functional theory', 'parallel binaries'],
'AFNI' : ['Magnetic Resonance Imaging (MRI)'],
'alphafold' : ['Chemistry'],
'alsa-lib' : ['Audio and Visualization Libraries and Tools'],
'ambertools' : ['Chemistry', 'Molecular Dynamics'],
'ampl' : ['Programming Language'],
'anicalculator': ['Genomics', 'Genomics - analytical tools',  'Genomics - classification tools'],
'ansys' : ['Engineering'],
'AnsysEM' : ['Engineering'],
'Ansys-Fluent' : ['Engineering'],
'ant' : ['Software Tools', 'java'],
'ants' : ['Magnetic Resonance Imaging (MRI)'],
'anvio' : ['Genomics', 'Genomics - analytical tools', 'Genomics - visualization tools'],
'aria' : ['Utilities and Command Line Interfaces (CLI)'],
'armadillo' : ['Numerical Methods'],
'ase' : ['Chemistry', 'Molecular Dynamics'],
'aspera' : ['Utilities and Command Line Interfaces (CLI)'],
'atk' : ['Chemistry'],
'ATLAS' : ['Numerical Methods'],
'atom' : ['Text Editor'],
'awscli' : ['Utilities and Command Line Interfaces (CLI)'],
'bam-readcount' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - analytical tools'],
'bamtools' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - analytical tools'],
'baron' : ['Numerical Methods'],
'bart' : ['Magnetic Resonance Imaging (MRI)'],
'basespace' : ['Genomics', 'Genomics - analytical tools', 'cloud'],
'bazel' : ['Compiler'],
'BBMap' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - RNA-seq'],
'bcbio_nextgen' : ['Genomics', 'python', 'Genomics - analytical tools'],
'BCBToolKit' : ['Genomics', 'python', 'Genomics - analytical tools'],
'bcftools' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics utlities - analytical pipelines'],
'bcl2fastq' : ['Genomics', 'Genomics - data conversion/transfer'],
'beagle-cpu' : ['Genomics', 'parallel', 'Genomics - analytical tools', 'Genomics - taxonomic/phylogenetic tools'],
'bedops' : ['Genomics', 'Genomics - analytical tools'],
'bedtools' : ['Genomics', 'Genomics - analytical tools'],
'bismark' : ['Genomics', 'Genomics - analytical tools', 'Genomics - epigenomic tools'],
'blas-lapack' : ['Numerical Methods'],
'blast' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - classification tools'],
'blatsuite' : ['Genomics', 'Genomics - sequence alignment'],
'blcr' : ['parallel', 'checkpointing', 'Software Tools'],
'boost' : ['Numerical Methods'],
'bowtie' : ['Genomics', 'Genomics - sequence alignment'],
'bowtie2' : ['Genomics', 'Genomics - sequence alignment'],
'bsmap' : ['Genomics', 'Genomics - analytical tools', 'Genomics - epigenomic tools'],
'bwa' : ['Genomics', 'Genomics - sequence alignment'],
'cairo' : ['Audio and Visualization Libraries and Tools'],
'casa' : ['astrophysics'],
'cassi' : ['Genomics', 'Genomics - variant calling/analysis'],
'cellranger' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - analytical tools', 'Genomics - RNA-seq'],
'cellranger-atac' : ['Genomics', 'Genomics - analytical tools'],
'CfitsIO' : ['Files and IO'],
'cgal' : ['Numerical Methods'],
'charm' : ['parallel'],
'charmpp' : ['parallel'],
'checkm' : ['Genomics', 'Genomics - quality assessment'],
'chemaxon_marvin' : ['Chemistry'],
'chemaxon_structure_rep' : ['Chemistry'],
'chimera' : ['Chemistry', 'Audio and Visualization Libraries and Tools'],
'clang' : ['Compiler'],
'cmake' : ['Software Tools'],
'cmdstan' : ['Programming Language'],
'connectome_workbench' : ['Magnetic Resonance Imaging (MRI)'],
'copasul' : ['Audio and Visualization Libraries and Tools'],
'cp2k' : ['Chemistry', 'Molecular Dynamics', 'quantum mechanics'],
'cplex' : ['Numerical Methods'],
'CrisprCasFinder' : ['Genomics', 'Genomics - analytical tools'],
'cuda' : ['Compiler'],
'cufflinks' : ['Genomics', 'Genomics - analytical tools', 'Genomics - RNA-seq'],
'curl' : ['Utilities and Command Line Interfaces (CLI)'],
'cytoscape' : ['Genomics', 'Genomics - analytical tools'],
'db' : ['Files and IO'],
'ddd' : ['Audio and Visualization Libraries and Tools'],
'deeptools' : ['Genomics', 'Genomics - analytical tools', 'Genomics - RNA-seq', 'Genomics - epigenomic tools'],
'diamond' : ['Genomics', 'Genomics - sequence alignment'],
'diffreps' : ['Genomics', 'Genomics - analytical tools', 'Genomics - epigenomic tools'],
'dynare' : ['economics'],
'dyninst' : ['Software Tools'],
'eclipse' : ['Software Tools', 'java'],
'eigen' : ['Numerical Methods'],
'elfutils' : ['Files and IO'],
'emacs' : ['Text Editor'],
'epacts' : ['Genomics', 'Genomics - analytical tools'],
'espresso' : ['Chemistry'],
'expansionhunter' : ['Genomics', 'Genomics - analytical tools'],
'expat' : ['Files and IO'],
'fastani' : ['Genomics', 'Genomics - analytical tools', 'Genomics - classification tools'],
'fastqc' : ['Genomics', 'Genomics - quality assessment'],
'fasttree' : ['Genomics', 'Genomics - taxonomic/phylogenetic tools'],
'FastTreeMP' : ['Genomics', 'Genomics - taxonomic/phylogenetic tools', 'parallel'],
'fenics27' : ['Compilers', 'finite element analysis', 'Engineering'],
'ffmpeg' : ['Files and IO', 'Audio and Visualization Libraries and Tools'],
'fftw' : ['Numerical Methods'],
'fMRIPrep' : ['Magnetic Resonance Imaging (MRI)'],
'freesurfer' : ['Magnetic Resonance Imaging (MRI)'],
'freetype' : ['Software Tools'],
'fsl' : ['Magnetic Resonance Imaging (MRI)'],
'gamess' : ['Chemistry'],
'gap' : ['Numerical Methods'],
'gatk' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics - analytical tools', 'Genomics - data conversion/transfer'],
'gauss' : ['Programming Language'],
'Gaussian' : ['Chemistry'],
'Gaussian16' : ['Chemistry'],
'gcc' : ['Compiler'],
'gcloud' : ['Utilities and Command Line Interfaces (CLI)'],
'gdal' : ['Files and IO'],
'gdb' : ['Software Tools'],
'gdbm' : ['Files and IO'],
'gdc-client' : ['Genomics', 'Genomics - data conversion/transfer'],
'gdk-pixbuf' : ['Audio and Visualization Libraries and Tools'],
'geany' : ['Text Editor'],
'GeneTorrent' : ['Genomics', 'Genomics - data conversion/transfer'],
'GenomeBrowse' : ['Genomics', 'Genomics - visualization tools'],
'geos' : ['Software Tools'],
'gettext' : ['Files and IO'],
'gffcompare' : ['Genomics', 'Genomics - RNA-seq', ''],
'gffread' : ['Genomics', 'Genomics - data conversion/transfer'],
'ghc' : ['Compiler'],
'ghostscript' : ['Programming Language'],
'git' : ['Utilities and Command Line Interfaces (CLI)', 'version control software'],
'gnumeric' : ['Audio and Visualization Libraries and Tools'],
'gnuplot' : ['Audio and Visualization Libraries and Tools'],
'go' : ['Programming Language'],
'gold' : ['Genomics'],
'GotoBlas' : ['Numerical Methods'],
'gpaw' : ['Chemistry', 'density functional theory'],
'grace' : ['Audio and Visualization Libraries and Tools'],
'gradle' : ['Software Tools', 'IDE'],
'graphlib' : ['Audio and Visualization Libraries and Tools'],
'graphviz' : ['Audio and Visualization Libraries and Tools'],
'GRASS' : ['Audio and Visualization Libraries and Tools'],
'gromacs' : ['Molecular Dynamics'],
'gsl' : ['Numerical Methods'],
'gstreamer' : ['Files and IO'],
'gtk+' : ['Audio and Visualization Libraries and Tools'],
'gtool' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics - analytical tools'],
'guppy' : ['Genomics', 'Genomics - visualization tools'],
'gurobi' : ['Numerical Methods'],
'hdf5' : ['Files and IO'],
'hic-pro' : ['Genomics', 'Genomics - analytical tools', 'Genomics - epigenomic tools'],
'hisat2' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - RNA-seq'],
'hmmer' : ['Genomics', 'Genomics - classification tools', 'Genomics - sequence alignment'],
'homer' : ['Genomics'],
'htslib' : ['Genomics', 'Genomics - sequence alignment'],
'hypre' : ['Numerical Methods'],
'icu4c' : ['Software Tools', 'java'],
'idba' : ['Genomics', 'Genomics - analytical tools', 'Genomics utilities - sequence assembler'],
'igv' : ['Genomics', 'Genomics - visualization tools'],
'ImageJ' : ['Magnetic Resonance Imaging (MRI)', 'Audio and Visualization Libraries and Tools'],
'ImageMagick' : ['Audio and Visualization Libraries and Tools'],
'impute2' : ['Genomics', 'Genomics - analytical tools'],
'imsl' : ['Numerical Methods'],
'indelocator' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics - analytical tools'],
'intel' : ['Compiler'],
'intel-mkl' : ['Numerical Methods'],
'intltool' : ['Files and IO'],
'ipopt' : ['Numerical Methods'],
'iread' : [],
'jags' : ['statistical computing'],
'java' : ['Programming Language'],
'jellyfish' : ['Genomics', 'parallel', 'Genomics - analytical tools'],
'jq' : ['Files and IO'],
'juicer' : ['Genomics'],
'julia' : ['Programming Language'],
'kallisto' : ['Genomics', 'Genomics - RNA-seq'],
'kentUtils' : ['Genomics', 'Genomics - analytical tools', 'Genomics - visualization tools'],
'kim-api' : ['Chemistry', 'Molecular Dynamics'],
'knitro' : ['Numerical Methods'],
'kraken' : ['Genomics', 'Genomics - taxonomic/phylogenetic tools'],
'krona' : ['Genomics', 'Genomics - visualization tools'],
'kSNP' : ['Genomics', 'Genomics - variant calling/analysis'],
'lammps' : ['Molecular Dynamics'],
'latte' : ['Molecular Dynamics'],
'lazarus' : ['Software Tools', 'IDE'],
'leptonica' : ['Audio and Visualization Libraries and Tools'],
'lftp' : ['Files and IO'],
'libreoffice' : ['Audio and Visualization Libraries and Tools'],
'liggghts-public' : ['Chemistry', 'Molecular Dynamics'],
'lp_solve' : ['Numerical Methods'],
'lumerical' : ['programmining language', 'Chemistry', 'FDTD'],
'MACS2' : ['Genomics', 'Genomics - analytical tools', 'Genomics - epigenomic tools'],
'mafft' : ['Genomics', 'Genomics - sequence alignment'],
'mageck' : ['Genomics', 'Genomics - analytical tools'],
'mageck_vispr' : ['Genomics', 'Genomics - analytical tools', 'Genomics - visualization tools'],
'makedepf90' : ['Software Tools'],
'manta' : ['Files and IO'],
'mathematica' : ['Programming Language', 'Numerical Methods'],
'matlab' : ['Programming Language', 'Numerical Methods'],
'matlabstan' : ['Numerical Methods'],
'meep' : ['Chemistry', 'FDTD'],
'megahit' : ['Genomics', 'Genomics - assembly tools'],
'meme' : ['Genomics', 'Genomics - analytical tools', 'Genomics - analytical tools'],
'mercurial' : ['Utilities and Command Line Interfaces (CLI)', 'version control software'],
'metabat' : ['Genomics', 'Genomics - analytical tools'],
'metal' : ['Genomics', 'Genomics - analytical tools', ''],
'metamap' : ['Files and IO'],
'metaxa2' : ['Genomics', 'Genomics - taxonomic/phylogenetic tools'],
'metis' : ['Genomics', 'annotation tools', 'Numerical Methods'],
'mlpack' : ['Numerical Methods'],
'mono' : ['Software Tools'],
'motif' : ['Audio and Visualization Libraries and Tools'],
'mpb' : ['Chemistry', 'Numerical Methods'],
'mpi' : ['parallel', 'Compiler'],
'mpi4py' : ['parallel'],
'mricrogl' : ['Magnetic Resonance Imaging (MRI)'],
'mrtrix3' : ['Magnetic Resonance Imaging (MRI)'],
'multiqc' : ['Genomics', 'Genomics - quality assessment'],
'mumps' : ['Numerical Methods'],
'muscle' : ['Genomics', 'Genomics - sequence alignment'],
'mutect' : ['Genomics', 'Genomics - analytical tools', 'Genomics - variant calling/analysis'],
'mysql' : ['Files and IO'],
'namd' : ['Molecular Dynamics'],
'nano' : ['Text Editor'],
'ncl' : ['Numerical Methods', 'Audio and Visualization Libraries and Tools'],
'nco' : ['Files and IO'],
'ncurses' : ['Audio and Visualization Libraries and Tools'],
'ndiff' : ['Files and IO'],
'netCDF' : ['Files and IO'],
'netcdf-c' : ['Files and IO'],
'netcdf-fortran' : ['Files and IO'],
'netlib-scalapack' : ['Numerical Methods'],
'netlogo' : ['Programming Language'],
'ngsplot' : ['Genomics', 'Genomics - visualization tools'],
'nlopt' : ['Numerical Methods'],
'novocraft' : ['Genomics', 'Genomics - analytical tools'],
'numpy' : ['Numerical Methods'],
'nwchem' : ['Chemistry', 'Molecular Dynamics', 'quantum mechanics'],
'ocaml' : ['Programming Language'],
'octave' : ['Programming Language'],
'oncotator' : ['Genomics', 'annotation tools', 'Genomics - variant calling/analysis'],
'openbabel' : ['Chemistry'],
'openblas' : ['Numerical Methods'],
'OpenBugs' : ['statistical computing'],
'opencl' : ['Programming Language'],
'openmd' : ['Molecular Dynamics'],
'orca' : ['Chemistry'],
'oxconsole' : ['IDE'],
'oxedit' : ['Text Editor'],
'p7zip' : ['Files and IO'],
'pandoc' : ['Files and IO'],
'papi' : ['Software Tools'],
'parallel' : ['parallel'],
'paraview' : ['Audio and Visualization Libraries and Tools'],
'parmetis' : ['Numerical Methods'],
'parsec' : ['Chemistry'],
'pBWA' : ['Genomics', 'Genomics - sequence alignment', 'parallel'],
'pdflib-lite' : ['Files and IO'],
'peer' : [],
'penncnv' : ['Genomics', 'Genomics - variant calling/analysis'],
'perl' : ['Programming Language'],
'petsc' : ['Numerical Methods'],
'pexsi' : ['Numerical Methods'],
'phylocsf' : ['Genomics', 'Genomics - RNA-seq'],
'picard' : ['Genomics', 'Genomics - analytical tools', 'Genomics - variant calling/analysis', 'Genomics - sequence alignment'],
'pigz' : ['Files and IO'],
'pindel' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics - variant calling/analysis', 'Genomics - analytical tools'],
'plink' : ['Genomics', 'Genomics - analytical tools', 'Genomics utilities - visualization tools'],
'plumed' : ['Molecular Dynamics'],
'poppler' : ['Files and IO'],
'povray' : ['Audio and Visualization Libraries and Tools'],
'pplacer' : ['Genomics', 'Genomics - analytical tools', 'Genomics - visualization tools'],
'prada' : ['Genomics', 'Genomics - analytical tools', 'Genomics - RNA-seq'],
'prodigal' : ['Genomics', 'annotation tools'],
'proj' : ['Numerical Methods'],
'protobuf' : ['Files and IO'],
'PRSice' : ['Genomics', 'Genomics - analytical tools'],
'python' : ['Programming Language'],
'python-anaconda3' : ['Programming Language'],
'python-miniconda3' : ['Programming Language'],
'qchem' : ['Chemistry'],
'qctool' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics - quality assessment'],
'qe' : ['Chemistry'],
'qhull' : ['Numerical Methods'],
'qiime2' : ['Genomics', 'Genomics - analytical tools', 'Genomics - taxonomic/phylogenetic tools'],
'qt' : ['Audio and Visualization Libraries and Tools'],
'qualimap' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - RNA-seq', 'Genomics - epigenomic tools'],
'quantum-espresso' : ['Chemistry'],
'R' : ['Programming Language', 'statistical computing'],
'raxml' : ['Genomics', 'Genomics - taxonomic/phylogenetic tools'],
'rfmix' : ['Genomics', 'Genomics - analytical tools', 'Genomics - taxonomic/phylogenetic tools'],
'rmats2sashimiplot' : ['Genomics', 'Genomics - visualization tools', 'Genomics - RNA-seq'],
'rmats_turbo' : ['Genomics', 'Genomics - analytical tools', 'Genomics - RNA-seq'],
'rsem' : ['Genomics', 'Genomics - analytical tools', 'Genomics - RNA-seq'],
'ruby' : ['Programming Language'],
'rufus' : ['Genomics', 'Genomics - analytical tools', 'Genomics - variant calling/analysis'],
'sage' : ['Genomics', 'Genomics - analytical tools', 'epidemiology tools'],
'sailfish' : ['Genomics', 'Genomics - analytical tools', 'Genomics - RNA-seq'],
'salmon' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - sequence alignment'],
'samtools' : ['Genomics', 'Genomics - sequence alignment'],
'sas' : ['Programming Language'],
'scala' : ['Programming Language'],
'scalapack' : ['Numerical Methods'],
'scallop' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - sequence alignment'],
'schrodinger' : ['Material Science', 'Engineering'],
'scons' : ['Software Tools'],
'sdpt3' : ['Numerical Methods'],
'seqkit' : ['Genomics', 'Genomics - analytical tools'],
'seqtk' : ['Genomics', 'Genomics - analytical tools'],
'shapeit' : ['Genomics', 'Genomics - analytical tools', 'Genomics - variant calling/analysis'],
'singularity' : ['Software Tools'],
'sirius' : ['Chemistry', 'Molecular Dynamics'],
'slepc' : ['Numerical Methods'],
'snakemake' : ['Utilities and Command Line Interfaces (CLI)'],
'snpEff' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - variant calling/analysis'],
'snptest' : ['Genomics', 'Genomics - variant calling/analysis'],
'soapdenovo2' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - assembly tools'],
'SolexaQA++' : ['Genomics', 'Genomics - quality assessment'],
'spades' : ['Genomics', 'Genomics - assembly tools'],
'spark' : ['Files and IO'],
'specfem3d_globe' : [],
'speedseq' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - assembly tools', 'Genomics - variant calling/analysis'],
'spfft' : ['Numerical Methods'],
'spglib' : ['Molecular Dynamics'],
'spla' : ['Numerical Methods'],
'spm' : ['Magnetic Resonance Imaging (MRI)'],
'sqlite' : ['Files and IO'],
'sratoolkit' : ['Genomics', 'Genomics - data conversion/transfer'],
'STAR' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - sequence alignment'],
'STAR-Fusion' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - sequence alignment'],
'stat' : ['Numerical Methods'],
'stata' : ['Programming Language'],
'stattransfer' : ['Files and IO'],
'strelka' : ['Genomics', 'Genomics - variant calling/analysis'],
'stress' : ['Software Tools'],
'stringtie' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - sequence alignment'],
'subread' : ['Genomics', 'Genomics - RNA-seq', 'Genomics - sequence alignment', 'Genomics - variant calling/analysis'],
'SuiteSparse' : ['Numerical Methods'],
'superlu' : ['Numerical Methods'],
'superlu-dist' : ['Numerical Methods'],
'suppa' : ['Genomics', 'Genomics - RNA-seq'],
'swig' : ['Software Tools'],
'tar' : ['Files and IO'],
'tau' : ['Software Tools'],
'tcl' : ['Programming Language'],
'telseq' : ['Genomics', 'Genomics - analytical tools'],
'tesseract' : [],
'texlive' : ['Compiler'],
'tickwrite' : ['economics'],
'tig' : ['Utilities and Command Line Interfaces (CLI)', 'version control software', 'git'],
'tmux' : ['Utilities and Command Line Interfaces (CLI)'],
'tophat' : ['Genomics', 'Genomics - RNA-seq'],
'Tramonto' : ['Material Science', 'Biology'],
'TrimGalore' : ['Genomics', 'Genomics - analytical tools'],
'trimmomatic' : ['Genomics', 'Genomics - analytical tools'],
'uchime' : ['Genomics', 'Genomics - quality assessment'],
'udunits2' : ['Software Tools'],
'utilities' : ['Utilities and Command Line Interfaces (CLI)', 'Software Tools'],
'valgrind' : ['Software Tools'],
'vasp' : ['Chemistry'],
'vcftools' : ['Genomics', 'Genomics - variant calling/analysis', 'Genomics - analytical tools'],
'velvet' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - assembly tools'],
'vesta' : ['Material Science', 'Audio and Visualization Libraries and Tools'],
'vim' : ['Text Editor'],
'visit' : ['Audio and Visualization Libraries and Tools'],
'vmd' : ['Molecular Dynamics', 'Audio and Visualization Libraries and Tools'],
'voropp' : ['Numerical Methods'],
'vtk' : ['Audio and Visualization Libraries and Tools'],
'wannier' : ['Chemistry'],
'wine' : ['Utilities and Command Line Interfaces (CLI)'],
'wxwidgets' : ['Audio and Visualization Libraries and Tools'],
'xander_assembler' : ['Genomics', 'Genomics - sequence alignment', 'Genomics - assembly tools'],
'xcb-proto' : ['Software Tools'],
'xmlsec' : ['Files and IO'],
'xpdf' : ['Files and IO'],
'xz' : ['Files and IO'],
'yaml-cpp' : ['Files and IO'],
'yasm' : ['Software Tools'],
'zstd' : ['Files and IO'],
}




LIST_OF_SOFTWARE = list(LIST_OF_MODULES_TO_SEARCH.keys())

# Create your views here.
letters_a_to_z = [ i for i in string.ascii_uppercase]

def index(request):
    modules = Module.objects.filter(name__in=LIST_OF_SOFTWARE)
    all_keywords = []
    for module in modules:
        if module.primary_keywords is not None:
            for keyword in module.primary_keywords:
                all_keywords.append(keyword)
    all_keywords = set(sorted(all_keywords))
    
    return render(request, 'modules/index.html', {"modules" : modules, "all_keywords" : all_keywords, 'letters_a_to_z' : letters_a_to_z})

def module_json(request):
    modules = Module.objects.filter(name__in=LIST_OF_SOFTWARE)
    modules_list = serializers.serialize('json', modules)
    return HttpResponse(modules_list, content_type="text/json-comment-filtered")
