from django.shortcuts import render, get_object_or_404
from .models import Module
from django.core import serializers
from django.http import HttpResponse
import string

LIST_OF_MODULES_TO_SEARCH = {
'abaqus' : ['finite element analysis', 'engineering'],
'abinit' : ['quantum chemistry', 'materials modeling', 'density functional theory', 'optimization', 'simulation'],
'ADF' : ['quantum chemistry', 'molecular dynamics', 'quantum mechanics', 'density functional theory', 'parallel binaries'],
'AFNI' : ['MRI'],
'alphafold' : ['chemistry'],
'alsa-lib' : [],
'ambertools' : ['molecular dynamics'],
'ampl' : [],
'anicalculator': ['genomics', 'ANI', 'genomics - classification tools'],
'ansys' : ['engineering'],
'AnsysEM' : ['engineering'],
'Ansys-Fluent' : ['engineering'],
'ant' : [],
'ants' : ['MRI'],
'anvio' : ['genomics', 'genomics - analytical tools', 'genomics utilities - visualization tools'],
'aria' : [],
'armadillo' : ['linear algebra'],
'ase' : ['molecular dynamics'],
'aspera' : [],
'atk' : ['quantum chemistry'],
'ATLAS' : ['linear algebra'],
'atom' : ['text editor'],
'at-spi2-atk' : [],
'at-spi2-core' : [],
'awscli' : [],
'bam-readcount' : ['genomics', 'genomics - RNA-seq', 'genomics - analytical tools'],
'bamtools' : ['genomics', 'genomics - sequence alignment', 'genomics - analytical tools'],
'baron' : [],
'bart' : [],
'basespace' : ['genomics', 'genomics - analytical tools', 'cloud'],
'bazel' : ['compiler'],
'BBMap' : ['genomics', 'genomics - sequence alignment', 'genomics - RNA-seq'],
'bcbio_nextgen' : ['genomics', 'python', 'genomics - analytical tools'],
'BCBToolKit' : ['genomics', 'python', 'genomics - analytical tools'],
'bcftools' : ['genomics', 'genomics - variant calling/analysis', 'genomics utlities - analytical pipelines'],
'bcl2fastq' : ['genomics', '', '', 'genomics - data conversion/transfer'],
'beagle-cpu' : [],
'bedops' : ['genomics', 'genomics - analytical tools'],
'bedtools' : ['genomics', 'genomics - analytical tools'],
'bismark' : ['genomics', 'bisulfite mapping', 'methylation calling'],
'blas-lapack' : ['linear algebra'],
'blast' : ['genomics', 'genomics - sequence alignment', 'genomics - classification tools'],
'blatsuite' : ['genomics', 'genomics - sequence alignment'],
'blcr' : [],
'boost' : ['linear algebra'],
'bowtie' : ['genomics', 'genomics - sequence alignment'],
'bowtie2' : ['genomics', 'genomics - sequence alignment'],
'bsmap' : ['genomics', 'genomics - analytical tools', 'bisulfite mapping', 'methylation calling'],
'bwa' : ['genomics', 'genomics - sequence alignment'],
'bwrap' : [],
'cairo' : [],
'casa' : [],
'cassi' : ['genomics', 'SNPs', 'genomics - variant calling/analysis'],
'cellranger' : ['genomics', 'genomics - sequence alignment', 'genomics - analytical tools', 'RNA-seq'],
'cellranger-atac' : ['genomics', 'genomics - analytical tools'],
'CfitsIO' : ['IO Libraries and Formats'],
'cgal' : [],
'charm' : ['parallel'],
'charmpp' : ['parallel'],
'checkm' : ['genomics', 'quality assessment'],
'chemaxon_marvin' : [],
'chemaxon_structure_rep' : [],
'chimera' : [],
'clang' : ['compiler'],
'cmake' : [],
'cmdstan' : [],
'connectome_workbench' : ['MRI'],
'copasul' : [],
'cp2k' : ['quantum chemistry', 'molecular dynamics', 'quantum mechanics'],
'cplex' : [],
'CrisprCasFinder' : ['genomics', 'genomics - analytical tools'],
'cuda' : ['compiler'],
'cufflinks' : ['genomics', 'genomics - analytical tools', 'genomics - RNA-seq'],
'curl' : [],
'cytoscape' : ['genomics', 'genomics - analytical tools'],
'db' : [],
'ddd' : [],
'deeptools' : ['genomics', 'genomics - analytical tools', 'genomics - RNA-seq', 'ChIP-seq', 'MNase-seq'],
'diamond' : ['genomics', 'genomics - sequence alignment'],
'diffreps' : ['genomics', 'genomics - analytical tools', 'ChIP-seq'],
'dynare' : [],
'dyninst' : [],
'eclipse' : [],
'eigen' : ['linear algebra'],
'elfutils' : [],
'emacs' : ['text editor'],
'epacts' : ['genomics', 'genomics - analytical tools'],
'espresso' : ['quantum chemistry'],
'expansionhunter' : ['genomics', 'genomics - analytical tools'],
'expat' : [],
'fastani' : ['genomics', 'ANI'],
'fastqc' : ['genomics', 'quality assessment'],
'fasttree' : ['genomics', 'genomics - taxonomic/phylogenetic tools'],
'FastTreeMP' : ['genomics', 'genomics - taxonomic/phylogenetic tools', 'parallel'],
'fenics27' : [],
'ffmpeg' : [],
'fftw' : [],
'fMRIPrep' : ['MRI'],
'freesurfer' : ['MRI'],
'freetype' : [],
'fsl' : ['MRI'],
'gamess' : ['quantum chemistry'],
'gap' : [],
'gatk' : ['genomics', 'SNPs', 'genomics - variant calling/analysis', 'genomics - analytical tools', 'genomics - data conversion/transfer'],
'gauss' : ['programming language'],
'Gaussian' : ['quantum chemistry'],
'Gaussian16' : ['quantum chemistry'],
'gcc' : ['compiler'],
'gcloud' : [],
'gdal' : [],
'gdb' : [],
'gdbm' : [],
'gdc-client' : ['genomics', 'genomics - data conversion/transfer'],
'gdk-pixbuf' : [],
'geany' : [],
'GeneTorrent' : ['genomics', 'genomics - data conversion/transfer'],
'GenomeBrowse' : ['genomics', 'visualization tools'],
'geos' : [],
'gettext' : [],
'gffcompare' : ['genomics', 'genomics - RNA-seq', ''],
'gffread' : ['genomics', 'genomics - data conversion/transfer'],
'ghc' : [],
'ghostscript' : [],
'git' : [],
'gnumeric' : [],
'gnuplot' : [],
'go' : [],
'gold' : [],
'GotoBlas' : [],
'gpaw' : [],
'grace' : [],
'gradle' : [],
'graphlib' : [],
'graphviz' : [],
'GRASS' : [],
'gromacs' : ['molecular dynamics'],
'gsl' : ['linear algebra'],
'gstreamer' : [],
'gtk+' : [],
'gtool' : ['genomics', 'SNPs', 'genomics - variant calling/analysis', 'genomics - analytical tools'],
'guppy' : ['genomics', 'visualization tools'],
'gurobi' : [],
'hdf5' : ['IO Libraries and Formats'],
'hic-pro' : ['genomics', 'genomics - analytical tools', 'Hi-C'],
'hisat2' : ['genomics', 'genomics - sequence alignment', 'genomics - RNA-seq'],
'hmmer' : ['genomics', 'genomics - classification tools', 'genomics - sequence alignment'],
'homer' : [],
'htslib' : ['genomics', 'genomics - sequence alignment'],
'hypre' : [],
'icu4c' : [],
'idba' : ['genomics', 'genomics - analytical tools', 'genomics utilities - sequence assembler'],
'igv' : ['genomics', 'visualization tools'],
'ImageJ' : [],
'ImageMagick' : [],
'impute2' : ['genomics', 'genomics - analytical tools'],
'imsl' : [],
'indelocator' : ['genomics', 'genomics - variant calling/analysis', 'genomics - analytical tools'],
'intel' : ['compiler'],
'intel-mkl' : ['linear algebra'],
'intltool' : [],
'ipopt' : [],
'iread' : [],
'jags' : ['statistical computing'],
'java' : [],
'jellyfish' : [],
'jq' : [],
'juicer' : [],
'julia' : ['programming language'],
'kallisto' : ['genomics', 'genomics - RNA-seq'],
'kentUtils' : ['genomics', 'genomics - analytical tools', 'genomics utilities - visualization tools'],
'kim-api' : [],
'knitro' : [],
'kraken' : ['genomics', 'genomics - taxonomic/phylogenetic tools'],
'krona' : ['genomics', 'visualization tools'],
'kSNP' : ['genomics', 'SNPs', 'genomics - variant calling/analysis'],
'lammps' : ['molecular dynamics'],
'latte' : [],
'launchmon' : [],
'lazarus' : [],
'leptonica' : [],
'lftp' : [],
'libreoffice' : [],
'liggghts-public' : [],
'lp_solve' : [],
'lumerical' : [],
'MACS2' : ['genomics', 'genomics - analytical tools', 'ChIP-seq'],
'mafft' : ['genomics', 'genomics - sequence alignment'],
'mageck' : ['genomics', 'genomics - analytical tools'],
'mageck_vispr' : ['genomics', 'genomics - analytical tools', 'visualization tools'],
'makedepf90' : [],
'manta' : [],
'mathematica' : ['programming language'],
'matlab' : ['programming language'],
'matlabstan' : [],
'meep' : [],
'megahit' : ['genomics', 'genomics - assembly tools'],
'meme' : ['genomics', 'genomics - analytical tools', 'genomics - analytical tools'],
'mercurial' : [],
'metabat' : ['genomics', 'genomics - analytical tools'],
'metal' : ['genomics', 'genomics - analytical tools', ''],
'metamap' : [],
'metaxa2' : ['genomics', 'genomics - taxonomic/phylogenetic tools'],
'metis' : ['genomics', 'annotation tools'],
'mlpack' : [],
'mono' : [],
'motif' : [],
'mpb' : [],
'mpi' : ['parallel', 'compiler'],
'mpi4py' : ['parallel'],
'mricrogl' : [],
'mrnet' : [],
'mrtrix3' : ['MRI'],
'MS-Ropen' : [],
'multiqc' : ['genomics', 'quality assessment'],
'mumps' : [],
'muscle' : ['genomics', 'genomics - sequence alignment'],
'mutect' : ['genomics', 'genomics - analytical tools', 'genomics - variant calling/analysis'],
'mysql' : [],
'namd' : ['molecular dynamics'],
'nano' : ['text editor'],
'ncl' : [],
'nco' : [],
'ncurses' : [],
'ndiff' : [],
'netCDF' : ['IO Libraries and Formats'],
'netcdf-c' : ['IO Libraries and Formats'],
'netcdf-fortran' : ['IO Libraries and Formats'],
'netlib-scalapack' : ['linear algebra'],
'netlogo' : [],
'ngsplot' : ['genomics', 'visualization tools'],
'nlopt' : [],
'novocraft' : ['genomics', 'genomics - analytical tools'],
'numactl' : [],
'numpy' : [],
'nwchem' : ['quantum chemistry', 'molecular dynamics', 'quantum mechanics'],
'ocaml' : [],
'octave' : ['programming language'],
'oncotator' : ['genomics', 'annotation tools', 'genomics - variant calling/analysis'],
'openbabel' : [],
'openblas' : ['linear algebra'],
'OpenBugs' : ['statistical computing'],
'opencl' : [],
'openmd' : ['molecular dynamics'],
'opera' : [],
'orca' : ['quantum chemistry'],
'osu-micro-benchmarks' : [],
'oxconsole' : [],
'oxedit' : [],
'p7zip' : [],
'pandoc' : [],
'papi' : [],
'parallel' : [],
'paraview' : [],
'parmetis' : [],
'parsec' : ['quantum chemistry'],
'pBWA' : ['genomics', 'genomics - sequence alignment', 'parallel'],
'pdflib-lite' : [],
'peer' : [],
'penncnv' : ['genomics', 'SNPs', 'genomics - variant calling/analysis'],
'perl' : ['programming language'],
'petsc' : [],
'pexsi' : [],
'phylocsf' : ['genomics', 'genomics - RNA-seq'],
'picard' : ['genomics', 'genomics - analytical tools', 'genomics - variant calling/analysis', 'genomics - sequence alignment'],
'pigz' : [],
'pindel' : ['genomics', 'genomics - variant calling/analysis', 'genomics - variant calling/analysis', 'genomics - analytical tools'],
'plink' : ['genomics', 'genomics - analytical tools', 'genomics utilities - visualization tools'],
'plumed' : ['molecular dynamics'],
'poppler' : [],
'povray' : [],
'pplacer' : ['genomics', 'genomics - analytical tools', 'genomics utilities - visualization tools'],
'prada' : ['genomics', 'genomics - analytical tools', 'genomics - RNA-seq'],
'prodigal' : ['genomics', 'annotation tools'],
'proj' : [],
'protobuf' : [],
'PRSice' : ['genomics', 'genomics - analytical tools'],
'python' : ['programming language'],
'python-anaconda3' : ['programming language'],
'python-miniconda3' : ['programming language'],
'qchem' : ['quantum chemistry'],
'qctool' : ['genomics', 'genomics - variant calling/analysis', 'genomics utilities - quality assessment'],
'qe' : ['quantum chemistry'],
'qhull' : [],
'qiime2' : ['genomics', 'genomics - analytical tools', 'genomics - taxonomic/phylogenetic tools'],
'qt' : [],
'qualimap' : ['genomics', 'genomics - sequence alignment', 'genomics - RNA-seq', 'ChIP-seq'],
'quantum-espresso' : ['quantum chemistry'],
'R' : ['programming language', 'statistical computing'],
'raxml' : ['genomics', 'genomics - taxonomic/phylogenetic tools'],
'rfmix' : ['genomics', 'genomics - analytical tools', 'genomics - taxonomic/phylogenetic tools'],
'rmats2sashimiplot' : ['genomics', 'visualization tools', 'genomics - RNA-seq'],
'rmats_turbo' : ['genomics', 'genomics - analytical tools', 'genomics - RNA-seq'],
'rsem' : ['genomics', 'genomics - analytical tools', 'genomics - RNA-seq'],
'ruby' : ['programming language'],
'rufus' : ['genomics', 'genomics - analytical tools', 'genomics - variant calling/analysis'],
'sage' : ['genomics', 'genomics - analytical tools', 'epidemiology tools'],
'sailfish' : [],
'salmon' : ['genomics', 'genomics - RNA-seq', 'genomics - sequence alignment'],
'samtools' : ['genomics', 'genomics - sequence alignment'],
'sas' : ['programming language'],
'scala' : [],
'scalapack' : ['linear algebra'],
'scallop' : ['genomics', 'genomics - RNA-seq', 'genomics - sequence alignment'],
'schrodinger' : [],
'scons' : [],
'sdpt3' : [],
'seqkit' : ['genomics', 'genomics - analytical tools'],
'seqtk' : ['genomics', 'genomics - analytical tools'],
'shapeit' : ['genomics', 'genomics - analytical tools', 'SNPs', 'genomics - variant calling/analysis'],
'singularity' : [],
'sirius' : [],
'slepc' : [],
'snakemake' : [],
'snpEff' : ['genomics', 'genomics - sequence alignment', 'SNPs', 'genomics - variant calling/analysis'],
'snptest' : ['genomics', 'SNPs', 'genomics - variant calling/analysis'],
'soapdenovo2' : ['genomics', 'genomics - sequence alignment', 'genomics - assembly tools'],
'SolexaQA++' : ['genomics', 'quality assessment'],
'spades' : ['genomics', 'genomics - assembly tools'],
'spark' : [],
'specfem3d_globe' : [],
'speedseq' : ['genomics', 'genomics - sequence alignment', 'genomics - assembly tools', 'SNPs', 'genomics - variant calling/analysis'],
'spfft' : [],
'spglib' : [],
'spla' : [],
'spm' : ['MRI'],
'sqlite' : [],
'sratoolkit' : ['genomics', 'genomics - data conversion/transfer'],
'STAR' : ['genomics', 'genomics - RNA-seq', 'genomics - sequence alignment'],
'STAR-Fusion' : ['genomics', 'genomics - RNA-seq', 'genomics - sequence alignment'],
'stat' : [],
'stata' : ['programming language'],
'stattransfer' : [],
'strelka' : ['genomics', 'genomics - variant calling/analysis'],
'stress' : [],
'stringtie' : ['genomics', 'genomics - RNA-seq', 'genomics - sequence alignment'],
'subread' : ['genomics', 'genomics - RNA-seq', 'genomics - sequence alignment', 'genomics - variant calling/analysis'],
'SuiteSparse' : [],
'superlu' : [],
'superlu-dist' : [],
'suppa' : ['genomics', 'genomics - RNA-seq'],
'swig' : [],
'tar' : [],
'tau' : [],
'tcl' : [],
'telseq' : ['genomics', 'genomics - analytical tools'],
'tesseract' : [],
'texlive' : [],
'tickwrite' : [],
'tig' : [],
'tmux' : [],
'tophat' : [],
'Tramonto' : [],
'TrimGalore' : ['genomics', 'genomics - analytical tools'],
'trimmomatic' : ['genomics', 'genomics - analytical tools'],
'uchime' : ['genomics', 'quality assessment'],
'udunits2' : [],
'utilities' : [],
'valgrind' : [],
'vasp' : ['quantum chemistry'],
'vcftools' : ['genomics', 'genomics - variant calling/analysis', 'genomics - analytical tools'],
'velvet' : ['genomics', 'genomics - sequence alignment', 'genomics - assembly tools'],
'vesta' : [],
'vim' : ['text editor'],
'visit' : [],
'vmd' : [],
'voropp' : [],
'vtk' : [],
'wannier' : ['quantum chemistry'],
'wine' : [],
'wxwidgets' : [],
'xander_assembler' : ['genomics', 'genomics - sequence alignment', 'genomics - assembly tools'],
'xcb-proto' : [],
'xmlsec' : [],
'xpdf' : [],
'xz' : [],
'yaml-cpp' : [],
'yasm' : [],
'zstd' : [],
}



LIST_OF_SOFTWARE = list(LIST_OF_MODULES_TO_SEARCH.keys())

# Create your views here.
letters_a_to_z = [ i for i in string.ascii_uppercase]

def index(request):
    modules = Module.objects.filter(name__in=LIST_OF_SOFTWARE)
    all_keywords = []
    for module in modules:
        if module.primary_keywords is not None:
            for keyword in module.primary_keywords:
                all_keywords.append(keyword)
    all_keywords = set(sorted(all_keywords))
    
    return render(request, 'modules/index.html', {"modules" : modules, "all_keywords" : all_keywords, 'letters_a_to_z' : letters_a_to_z})

def module_json(request):
    modules = Module.objects.filter(name__in=LIST_OF_SOFTWARE)
    modules_list = serializers.serialize('json', modules)
    return HttpResponse(modules_list, content_type="text/json-comment-filtered")
