# Generated by Django 3.1.7 on 2021-03-06 18:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='The name of the module/software')),
                ('versions', models.JSONField(verbose_name='All still avaialble versions of this software')),
                ('preferred', models.CharField(help_text='preferred version of this module (possibly should also be the default)', max_length=100)),
                ('html_text', ckeditor.fields.RichTextField(blank=True, help_text='Information about this module.', null=True)),
            ],
        ),
    ]
