# Generated by Django 3.1.7 on 2021-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(help_text='The name of the module/software', max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='preferred',
            field=models.CharField(blank=True, help_text='preferred version of this module (possibly should also be the default)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='versions',
            field=models.JSONField(blank=True, help_text='All still avaialble versions of this software', null=True),
        ),
    ]
