# Generated by Django 3.1.7 on 2021-03-06 21:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20210306_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='html_text',
        ),
        migrations.AddField(
            model_name='module',
            name='help_info',
            field=ckeditor.fields.RichTextField(blank=True, help_text='module help that comes from running module help XXX.', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='slurm_submission_example',
            field=ckeditor.fields.RichTextField(blank=True, help_text='module whatis that comes from running module whatis', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='whatis',
            field=ckeditor.fields.RichTextField(blank=True, help_text='module whatis that comes from running module whatis', null=True),
        ),
    ]
