# Generated by Django 3.1.7 on 2021-03-14 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_auto_20210306_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_version', models.CharField(blank=True, help_text='preferred version of this software according to spack', max_length=100, null=True)),
                ('compiler', models.CharField(choices=[('gcc@4.8.5', 'GCC 4.8.5'), ('gcc@10.2.0', 'GCC 10.2.0'), ('intel@19.0.5.281', 'INTEL 19.0.5.281')], help_text='If we were to build this module using spack, what compiler should be used', max_length=100)),
                ('variants_available', models.JSONField(blank=True, help_text='What variants are allowed for this module', null=True)),
                ('variants_enabled', models.JSONField(blank=True, help_text='List with length variants_available that indicates which variants we decided to turn off or on.', null=True)),
                ('arch', models.CharField(default='linux-rhel7-x86_64', max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module')),
            ],
        ),
    ]
