# Generated by Django 3.1.7 on 2021-03-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_spack_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spack',
            name='compiler',
            field=models.CharField(choices=[('gcc@4.8.5', 'GCC 4.8.5'), ('gcc@10.2.0', 'GCC 10.2.0'), ('intel@19.0.5.281', 'INTEL 19.0.5.281')], default='gcc@4.8.5', help_text='If we were to build this module using spack, what compiler should be used', max_length=100),
        ),
    ]
