# Generated by Django 3.1.7 on 2021-04-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_auto_20210325_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='keywords',
        ),
        migrations.AddField(
            model_name='module',
            name='primary_keywords',
            field=models.JSONField(blank=True, help_text='Primary top-level words to describe the use of this module like chemistry or data analysis.', null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='secondary_keywords',
            field=models.JSONField(blank=True, help_text='Additional words that might be used to describe the purposes of this software like DFT.', null=True),
        ),
    ]
